/* Auto-generated by genmsg_cpp for file /home/beryl/fuerte_workspace/sandbox/humanoid_navigation_ros/arm_navigation/arm_navigation_msgs/msg/LinkPadding.msg */
#ifndef ARM_NAVIGATION_MSGS_MESSAGE_LINKPADDING_H
#define ARM_NAVIGATION_MSGS_MESSAGE_LINKPADDING_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arm_navigation_msgs
{
template <class ContainerAllocator>
struct LinkPadding_ {
  typedef LinkPadding_<ContainerAllocator> Type;

  LinkPadding_()
  : link_name()
  , padding(0.0)
  {
  }

  LinkPadding_(const ContainerAllocator& _alloc)
  : link_name(_alloc)
  , padding(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _link_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  link_name;

  typedef double _padding_type;
  double padding;


  typedef boost::shared_ptr< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LinkPadding
typedef  ::arm_navigation_msgs::LinkPadding_<std::allocator<void> > LinkPadding;

typedef boost::shared_ptr< ::arm_navigation_msgs::LinkPadding> LinkPaddingPtr;
typedef boost::shared_ptr< ::arm_navigation_msgs::LinkPadding const> LinkPaddingConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_navigation_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b3ea75670df55c696fedee97774d5947";
  }

  static const char* value(const  ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb3ea75670df55c69ULL;
  static const uint64_t static_value2 = 0x6fedee97774d5947ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_navigation_msgs/LinkPadding";
  }

  static const char* value(const  ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#name for the link\n\
string link_name\n\
\n\
# padding to apply to the link\n\
float64 padding\n\
\n\
";
  }

  static const char* value(const  ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.link_name);
    stream.next(m.padding);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LinkPadding_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> & v) 
  {
    s << indent << "link_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.link_name);
    s << indent << "padding: ";
    Printer<double>::stream(s, indent + "  ", v.padding);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_NAVIGATION_MSGS_MESSAGE_LINKPADDING_H

