/* Auto-generated by genmsg_cpp for file /home/beryl/fuerte_workspace/sandbox/humanoid_navigation_ros/arm_navigation/arm_navigation_msgs/msg/MakeStaticCollisionMapFeedback.msg */
#ifndef ARM_NAVIGATION_MSGS_MESSAGE_MAKESTATICCOLLISIONMAPFEEDBACK_H
#define ARM_NAVIGATION_MSGS_MESSAGE_MAKESTATICCOLLISIONMAPFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arm_navigation_msgs
{
template <class ContainerAllocator>
struct MakeStaticCollisionMapFeedback_ {
  typedef MakeStaticCollisionMapFeedback_<ContainerAllocator> Type;

  MakeStaticCollisionMapFeedback_()
  {
  }

  MakeStaticCollisionMapFeedback_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MakeStaticCollisionMapFeedback
typedef  ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<std::allocator<void> > MakeStaticCollisionMapFeedback;

typedef boost::shared_ptr< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback> MakeStaticCollisionMapFeedbackPtr;
typedef boost::shared_ptr< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback const> MakeStaticCollisionMapFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_navigation_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_navigation_msgs/MakeStaticCollisionMapFeedback";
  }

  static const char* value(const  ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
\n\
";
  }

  static const char* value(const  ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MakeStaticCollisionMapFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_navigation_msgs::MakeStaticCollisionMapFeedback_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_NAVIGATION_MSGS_MESSAGE_MAKESTATICCOLLISIONMAPFEEDBACK_H

