/* Auto-generated by genmsg_cpp for file /home/beryl/fuerte_workspace/sandbox/humanoid_navigation_ros/arm_navigation/arm_navigation_msgs/msg/MakeStaticCollisionMapGoal.msg */
#ifndef ARM_NAVIGATION_MSGS_MESSAGE_MAKESTATICCOLLISIONMAPGOAL_H
#define ARM_NAVIGATION_MSGS_MESSAGE_MAKESTATICCOLLISIONMAPGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arm_navigation_msgs
{
template <class ContainerAllocator>
struct MakeStaticCollisionMapGoal_ {
  typedef MakeStaticCollisionMapGoal_<ContainerAllocator> Type;

  MakeStaticCollisionMapGoal_()
  : cloud_source()
  , number_of_clouds(0)
  {
  }

  MakeStaticCollisionMapGoal_(const ContainerAllocator& _alloc)
  : cloud_source(_alloc)
  , number_of_clouds(0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cloud_source_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  cloud_source;

  typedef int32_t _number_of_clouds_type;
  int32_t number_of_clouds;


  typedef boost::shared_ptr< ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MakeStaticCollisionMapGoal
typedef  ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<std::allocator<void> > MakeStaticCollisionMapGoal;

typedef boost::shared_ptr< ::arm_navigation_msgs::MakeStaticCollisionMapGoal> MakeStaticCollisionMapGoalPtr;
typedef boost::shared_ptr< ::arm_navigation_msgs::MakeStaticCollisionMapGoal const> MakeStaticCollisionMapGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_navigation_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "43564281ea7e3c1ca0f01095edc909f7";
  }

  static const char* value(const  ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x43564281ea7e3c1cULL;
  static const uint64_t static_value2 = 0xa0f01095edc909f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_navigation_msgs/MakeStaticCollisionMapGoal";
  }

  static const char* value(const  ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#The source to use to make the stable map\n\
string cloud_source\n\
\n\
#The number of clouds to compose the stable map\n\
int32 number_of_clouds\n\
\n\
";
  }

  static const char* value(const  ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.cloud_source);
    stream.next(m.number_of_clouds);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MakeStaticCollisionMapGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_navigation_msgs::MakeStaticCollisionMapGoal_<ContainerAllocator> & v) 
  {
    s << indent << "cloud_source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cloud_source);
    s << indent << "number_of_clouds: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number_of_clouds);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_NAVIGATION_MSGS_MESSAGE_MAKESTATICCOLLISIONMAPGOAL_H

