/* Auto-generated by genmsg_cpp for file /home/beryl/fuerte_workspace/sandbox/humanoid_navigation_ros/arm_navigation/arm_navigation_msgs/msg/MotionPlanRequest.msg */
#ifndef ARM_NAVIGATION_MSGS_MESSAGE_MOTIONPLANREQUEST_H
#define ARM_NAVIGATION_MSGS_MESSAGE_MOTIONPLANREQUEST_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "arm_navigation_msgs/WorkspaceParameters.h"
#include "arm_navigation_msgs/RobotState.h"
#include "arm_navigation_msgs/Constraints.h"
#include "arm_navigation_msgs/Constraints.h"

namespace arm_navigation_msgs
{
template <class ContainerAllocator>
struct MotionPlanRequest_ {
  typedef MotionPlanRequest_<ContainerAllocator> Type;

  MotionPlanRequest_()
  : workspace_parameters()
  , start_state()
  , goal_constraints()
  , path_constraints()
  , planner_id()
  , group_name()
  , num_planning_attempts(0)
  , allowed_planning_time()
  , expected_path_duration()
  , expected_path_dt()
  {
  }

  MotionPlanRequest_(const ContainerAllocator& _alloc)
  : workspace_parameters(_alloc)
  , start_state(_alloc)
  , goal_constraints(_alloc)
  , path_constraints(_alloc)
  , planner_id(_alloc)
  , group_name(_alloc)
  , num_planning_attempts(0)
  , allowed_planning_time()
  , expected_path_duration()
  , expected_path_dt()
  {
  }

  typedef  ::arm_navigation_msgs::WorkspaceParameters_<ContainerAllocator>  _workspace_parameters_type;
   ::arm_navigation_msgs::WorkspaceParameters_<ContainerAllocator>  workspace_parameters;

  typedef  ::arm_navigation_msgs::RobotState_<ContainerAllocator>  _start_state_type;
   ::arm_navigation_msgs::RobotState_<ContainerAllocator>  start_state;

  typedef  ::arm_navigation_msgs::Constraints_<ContainerAllocator>  _goal_constraints_type;
   ::arm_navigation_msgs::Constraints_<ContainerAllocator>  goal_constraints;

  typedef  ::arm_navigation_msgs::Constraints_<ContainerAllocator>  _path_constraints_type;
   ::arm_navigation_msgs::Constraints_<ContainerAllocator>  path_constraints;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _planner_id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  planner_id;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _group_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  group_name;

  typedef int32_t _num_planning_attempts_type;
  int32_t num_planning_attempts;

  typedef ros::Duration _allowed_planning_time_type;
  ros::Duration allowed_planning_time;

  typedef ros::Duration _expected_path_duration_type;
  ros::Duration expected_path_duration;

  typedef ros::Duration _expected_path_dt_type;
  ros::Duration expected_path_dt;


  typedef boost::shared_ptr< ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MotionPlanRequest
typedef  ::arm_navigation_msgs::MotionPlanRequest_<std::allocator<void> > MotionPlanRequest;

typedef boost::shared_ptr< ::arm_navigation_msgs::MotionPlanRequest> MotionPlanRequestPtr;
typedef boost::shared_ptr< ::arm_navigation_msgs::MotionPlanRequest const> MotionPlanRequestConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_navigation_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "75408e881303c6ad5069bd5df65ecb00";
  }

  static const char* value(const  ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x75408e881303c6adULL;
  static const uint64_t static_value2 = 0x5069bd5df65ecb00ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_navigation_msgs/MotionPlanRequest";
  }

  static const char* value(const  ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This service contains the definition for a request to the motion\n\
# planner and the output it provides\n\
\n\
# Parameters for the workspace that the planner should work inside\n\
arm_navigation_msgs/WorkspaceParameters workspace_parameters\n\
\n\
# Starting state updates. If certain joints should be considered\n\
# at positions other than the current ones, these positions should\n\
# be set here\n\
arm_navigation_msgs/RobotState start_state\n\
\n\
# The goal state for the model to plan for. The goal is achieved\n\
# if all constraints are satisfied\n\
arm_navigation_msgs/Constraints goal_constraints\n\
\n\
# No state at any point along the path in the produced motion plan will violate these constraints\n\
arm_navigation_msgs/Constraints path_constraints\n\
\n\
# The name of the motion planner to use. If no name is specified,\n\
# a default motion planner will be used\n\
string planner_id\n\
\n\
# The name of the group of joints on which this planner is operating\n\
string group_name\n\
\n\
# The number of times this plan is to be computed. Shortest solution\n\
# will be reported.\n\
int32 num_planning_attempts\n\
\n\
# The maximum amount of time the motion planner is allowed to plan for\n\
duration allowed_planning_time\n\
\n\
# An expected path duration (in seconds) along with an expected discretization of the path allows the planner to determine the discretization of the trajectory that it returns\n\
duration expected_path_duration\n\
duration expected_path_dt\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/WorkspaceParameters\n\
# This message contains a set of parameters useful in\n\
# setting up the workspace for planning\n\
arm_navigation_msgs/Shape  workspace_region_shape\n\
geometry_msgs/PoseStamped    workspace_region_pose\n\
\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/Shape\n\
byte SPHERE=0\n\
byte BOX=1\n\
byte CYLINDER=2\n\
byte MESH=3\n\
\n\
byte type\n\
\n\
\n\
#### define sphere, box, cylinder ####\n\
# the origin of each shape is considered at the shape's center\n\
\n\
# for sphere\n\
# radius := dimensions[0]\n\
\n\
# for cylinder\n\
# radius := dimensions[0]\n\
# length := dimensions[1]\n\
# the length is along the Z axis\n\
\n\
# for box\n\
# size_x := dimensions[0]\n\
# size_y := dimensions[1]\n\
# size_z := dimensions[2]\n\
float64[] dimensions\n\
\n\
\n\
#### define mesh ####\n\
\n\
# list of triangles; triangle k is defined by tre vertices located\n\
# at indices triangles[3k], triangles[3k+1], triangles[3k+2]\n\
int32[] triangles\n\
geometry_msgs/Point[] vertices\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/RobotState\n\
# This message contains information about the robot state, i.e. the positions of its joints and links\n\
sensor_msgs/JointState joint_state\n\
arm_navigation_msgs/MultiDOFJointState multi_dof_joint_state\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/MultiDOFJointState\n\
#A representation of a multi-dof joint state\n\
time stamp\n\
string[] joint_names\n\
string[] frame_ids\n\
string[] child_frame_ids\n\
geometry_msgs/Pose[] poses\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/Constraints\n\
# This message contains a list of motion planning constraints.\n\
\n\
arm_navigation_msgs/JointConstraint[] joint_constraints\n\
arm_navigation_msgs/PositionConstraint[] position_constraints\n\
arm_navigation_msgs/OrientationConstraint[] orientation_constraints\n\
arm_navigation_msgs/VisibilityConstraint[] visibility_constraints\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/JointConstraint\n\
# Constrain the position of a joint to be within a certain bound\n\
string joint_name\n\
\n\
# the bound to be achieved is [position - tolerance_below, position + tolerance_above]\n\
float64 position\n\
float64 tolerance_above\n\
float64 tolerance_below\n\
\n\
# A weighting factor for this constraint\n\
float64 weight\n\
================================================================================\n\
MSG: arm_navigation_msgs/PositionConstraint\n\
# This message contains the definition of a position constraint.\n\
Header header\n\
\n\
# The robot link this constraint refers to\n\
string link_name\n\
\n\
# The offset (in the link frame) for the target point on the link we are planning for\n\
geometry_msgs/Point target_point_offset\n\
\n\
# The nominal/target position for the point we are planning for\n\
geometry_msgs/Point position\n\
\n\
# The shape of the bounded region that constrains the position of the end-effector\n\
# This region is always centered at the position defined above\n\
arm_navigation_msgs/Shape constraint_region_shape\n\
\n\
# The orientation of the bounded region that constrains the position of the end-effector. \n\
# This allows the specification of non-axis aligned constraints\n\
geometry_msgs/Quaternion constraint_region_orientation\n\
\n\
# Constraint weighting factor - a weight for this constraint\n\
float64 weight\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/OrientationConstraint\n\
# This message contains the definition of an orientation constraint.\n\
Header header\n\
\n\
# The robot link this constraint refers to\n\
string link_name\n\
\n\
# The type of the constraint\n\
int32 type\n\
int32 LINK_FRAME=0\n\
int32 HEADER_FRAME=1\n\
\n\
# The desired orientation of the robot link specified as a quaternion\n\
geometry_msgs/Quaternion orientation\n\
\n\
# optional RPY error tolerances specified if \n\
float64 absolute_roll_tolerance\n\
float64 absolute_pitch_tolerance\n\
float64 absolute_yaw_tolerance\n\
\n\
# Constraint weighting factor - a weight for this constraint\n\
float64 weight\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/VisibilityConstraint\n\
# This message contains the definition of a visibility constraint.\n\
Header header\n\
\n\
# The point stamped target that needs to be kept within view of the sensor\n\
geometry_msgs/PointStamped target\n\
\n\
# The local pose of the frame in which visibility is to be maintained\n\
# The frame id should represent the robot link to which the sensor is attached\n\
# The visual axis of the sensor is assumed to be along the X axis of this frame\n\
geometry_msgs/PoseStamped sensor_pose\n\
\n\
# The deviation (in radians) that will be tolerated\n\
# Constraint error will be measured as the solid angle between the \n\
# X axis of the frame defined above and the vector between the origin \n\
# of the frame defined above and the target location\n\
float64 absolute_tolerance\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
";
  }

  static const char* value(const  ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.workspace_parameters);
    stream.next(m.start_state);
    stream.next(m.goal_constraints);
    stream.next(m.path_constraints);
    stream.next(m.planner_id);
    stream.next(m.group_name);
    stream.next(m.num_planning_attempts);
    stream.next(m.allowed_planning_time);
    stream.next(m.expected_path_duration);
    stream.next(m.expected_path_dt);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MotionPlanRequest_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_navigation_msgs::MotionPlanRequest_<ContainerAllocator> & v) 
  {
    s << indent << "workspace_parameters: ";
s << std::endl;
    Printer< ::arm_navigation_msgs::WorkspaceParameters_<ContainerAllocator> >::stream(s, indent + "  ", v.workspace_parameters);
    s << indent << "start_state: ";
s << std::endl;
    Printer< ::arm_navigation_msgs::RobotState_<ContainerAllocator> >::stream(s, indent + "  ", v.start_state);
    s << indent << "goal_constraints: ";
s << std::endl;
    Printer< ::arm_navigation_msgs::Constraints_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_constraints);
    s << indent << "path_constraints: ";
s << std::endl;
    Printer< ::arm_navigation_msgs::Constraints_<ContainerAllocator> >::stream(s, indent + "  ", v.path_constraints);
    s << indent << "planner_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.planner_id);
    s << indent << "group_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.group_name);
    s << indent << "num_planning_attempts: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_planning_attempts);
    s << indent << "allowed_planning_time: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.allowed_planning_time);
    s << indent << "expected_path_duration: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.expected_path_duration);
    s << indent << "expected_path_dt: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.expected_path_dt);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_NAVIGATION_MSGS_MESSAGE_MOTIONPLANREQUEST_H

