/* Auto-generated by genmsg_cpp for file /home/beryl/fuerte_workspace/sandbox/humanoid_navigation_ros/arm_navigation/arm_navigation_msgs/msg/PlanningScene.msg */
#ifndef ARM_NAVIGATION_MSGS_MESSAGE_PLANNINGSCENE_H
#define ARM_NAVIGATION_MSGS_MESSAGE_PLANNINGSCENE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "arm_navigation_msgs/RobotState.h"
#include "geometry_msgs/TransformStamped.h"
#include "arm_navigation_msgs/AllowedCollisionMatrix.h"
#include "arm_navigation_msgs/AllowedContactSpecification.h"
#include "arm_navigation_msgs/LinkPadding.h"
#include "arm_navigation_msgs/CollisionObject.h"
#include "arm_navigation_msgs/AttachedCollisionObject.h"
#include "arm_navigation_msgs/CollisionMap.h"

namespace arm_navigation_msgs
{
template <class ContainerAllocator>
struct PlanningScene_ {
  typedef PlanningScene_<ContainerAllocator> Type;

  PlanningScene_()
  : robot_state()
  , fixed_frame_transforms()
  , allowed_collision_matrix()
  , allowed_contacts()
  , link_padding()
  , collision_objects()
  , attached_collision_objects()
  , collision_map()
  {
  }

  PlanningScene_(const ContainerAllocator& _alloc)
  : robot_state(_alloc)
  , fixed_frame_transforms(_alloc)
  , allowed_collision_matrix(_alloc)
  , allowed_contacts(_alloc)
  , link_padding(_alloc)
  , collision_objects(_alloc)
  , attached_collision_objects(_alloc)
  , collision_map(_alloc)
  {
  }

  typedef  ::arm_navigation_msgs::RobotState_<ContainerAllocator>  _robot_state_type;
   ::arm_navigation_msgs::RobotState_<ContainerAllocator>  robot_state;

  typedef std::vector< ::geometry_msgs::TransformStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::other >  _fixed_frame_transforms_type;
  std::vector< ::geometry_msgs::TransformStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::other >  fixed_frame_transforms;

  typedef  ::arm_navigation_msgs::AllowedCollisionMatrix_<ContainerAllocator>  _allowed_collision_matrix_type;
   ::arm_navigation_msgs::AllowedCollisionMatrix_<ContainerAllocator>  allowed_collision_matrix;

  typedef std::vector< ::arm_navigation_msgs::AllowedContactSpecification_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::arm_navigation_msgs::AllowedContactSpecification_<ContainerAllocator> >::other >  _allowed_contacts_type;
  std::vector< ::arm_navigation_msgs::AllowedContactSpecification_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::arm_navigation_msgs::AllowedContactSpecification_<ContainerAllocator> >::other >  allowed_contacts;

  typedef std::vector< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> >::other >  _link_padding_type;
  std::vector< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> >::other >  link_padding;

  typedef std::vector< ::arm_navigation_msgs::CollisionObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::arm_navigation_msgs::CollisionObject_<ContainerAllocator> >::other >  _collision_objects_type;
  std::vector< ::arm_navigation_msgs::CollisionObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::arm_navigation_msgs::CollisionObject_<ContainerAllocator> >::other >  collision_objects;

  typedef std::vector< ::arm_navigation_msgs::AttachedCollisionObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::arm_navigation_msgs::AttachedCollisionObject_<ContainerAllocator> >::other >  _attached_collision_objects_type;
  std::vector< ::arm_navigation_msgs::AttachedCollisionObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::arm_navigation_msgs::AttachedCollisionObject_<ContainerAllocator> >::other >  attached_collision_objects;

  typedef  ::arm_navigation_msgs::CollisionMap_<ContainerAllocator>  _collision_map_type;
   ::arm_navigation_msgs::CollisionMap_<ContainerAllocator>  collision_map;


  typedef boost::shared_ptr< ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_navigation_msgs::PlanningScene_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PlanningScene
typedef  ::arm_navigation_msgs::PlanningScene_<std::allocator<void> > PlanningScene;

typedef boost::shared_ptr< ::arm_navigation_msgs::PlanningScene> PlanningScenePtr;
typedef boost::shared_ptr< ::arm_navigation_msgs::PlanningScene const> PlanningSceneConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_navigation_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::PlanningScene_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6d1add8ef6efdd62d194ef430abd4b75";
  }

  static const char* value(const  ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6d1add8ef6efdd62ULL;
  static const uint64_t static_value2 = 0xd194ef430abd4b75ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_navigation_msgs/PlanningScene";
  }

  static const char* value(const  ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#full robot state\n\
arm_navigation_msgs/RobotState robot_state\n\
\n\
#additional frames for duplicating tf\n\
geometry_msgs/TransformStamped[] fixed_frame_transforms\n\
\n\
#full allowed collision matrix\n\
AllowedCollisionMatrix allowed_collision_matrix\n\
\n\
#allowed contacts\n\
arm_navigation_msgs/AllowedContactSpecification[] allowed_contacts\n\
\n\
#all link paddings\n\
arm_navigation_msgs/LinkPadding[] link_padding\n\
\n\
#collision objects\n\
arm_navigation_msgs/CollisionObject[] collision_objects\n\
arm_navigation_msgs/AttachedCollisionObject[] attached_collision_objects\n\
\n\
#the collision map\n\
arm_navigation_msgs/CollisionMap collision_map\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/RobotState\n\
# This message contains information about the robot state, i.e. the positions of its joints and links\n\
sensor_msgs/JointState joint_state\n\
arm_navigation_msgs/MultiDOFJointState multi_dof_joint_state\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/MultiDOFJointState\n\
#A representation of a multi-dof joint state\n\
time stamp\n\
string[] joint_names\n\
string[] frame_ids\n\
string[] child_frame_ids\n\
geometry_msgs/Pose[] poses\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TransformStamped\n\
# This expresses a transform from coordinate frame header.frame_id\n\
# to the coordinate frame child_frame_id\n\
#\n\
# This message is mostly used by the \n\
# <a href=\"http://www.ros.org/wiki/tf\">tf</a> package. \n\
# See it's documentation for more information.\n\
\n\
Header header\n\
string child_frame_id # the frame id of the child frame\n\
Transform transform\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Transform\n\
# This represents the transform between two coordinate frames in free space.\n\
\n\
Vector3 translation\n\
Quaternion rotation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: arm_navigation_msgs/AllowedCollisionMatrix\n\
# the list of link names in the matrix\n\
string[] link_names\n\
\n\
# the individual entries in the allowed collision matrix\n\
# symmetric, with same order as link_names\n\
AllowedCollisionEntry[] entries\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/AllowedCollisionEntry\n\
# whether or not collision checking is enabled\n\
bool[] enabled\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/AllowedContactSpecification\n\
# The names of the regions\n\
string name\n\
\n\
# The shape of the region in the environment\n\
arm_navigation_msgs/Shape shape\n\
\n\
# The pose of the space defining the region\n\
geometry_msgs/PoseStamped pose_stamped\n\
\n\
# The set of links that will be allowed to have penetration contact within this region\n\
string[] link_names\n\
\n\
# The maximum penetration depth allowed for every link\n\
float64 penetration_depth\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/Shape\n\
byte SPHERE=0\n\
byte BOX=1\n\
byte CYLINDER=2\n\
byte MESH=3\n\
\n\
byte type\n\
\n\
\n\
#### define sphere, box, cylinder ####\n\
# the origin of each shape is considered at the shape's center\n\
\n\
# for sphere\n\
# radius := dimensions[0]\n\
\n\
# for cylinder\n\
# radius := dimensions[0]\n\
# length := dimensions[1]\n\
# the length is along the Z axis\n\
\n\
# for box\n\
# size_x := dimensions[0]\n\
# size_y := dimensions[1]\n\
# size_z := dimensions[2]\n\
float64[] dimensions\n\
\n\
\n\
#### define mesh ####\n\
\n\
# list of triangles; triangle k is defined by tre vertices located\n\
# at indices triangles[3k], triangles[3k+1], triangles[3k+2]\n\
int32[] triangles\n\
geometry_msgs/Point[] vertices\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/LinkPadding\n\
#name for the link\n\
string link_name\n\
\n\
# padding to apply to the link\n\
float64 padding\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/CollisionObject\n\
# a header, used for interpreting the poses\n\
Header header\n\
\n\
# the id of the object\n\
string id\n\
\n\
# The padding used for filtering points near the object.\n\
# This does not affect collision checking for the object.  \n\
# Set to negative to get zero padding.\n\
float32 padding\n\
\n\
#This contains what is to be done with the object\n\
CollisionObjectOperation operation\n\
\n\
#the shapes associated with the object\n\
arm_navigation_msgs/Shape[] shapes\n\
\n\
#the poses associated with the shapes - will be transformed using the header\n\
geometry_msgs/Pose[] poses\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/CollisionObjectOperation\n\
#Puts the object into the environment\n\
#or updates the object if already added\n\
byte ADD=0\n\
\n\
#Removes the object from the environment entirely\n\
byte REMOVE=1\n\
\n\
#Only valid within the context of a CollisionAttachedObject message\n\
#Will be ignored if sent with an CollisionObject message\n\
#Takes an attached object, detaches from the attached link\n\
#But adds back in as regular object\n\
byte DETACH_AND_ADD_AS_OBJECT=2\n\
\n\
#Only valid within the context of a CollisionAttachedObject message\n\
#Will be ignored if sent with an CollisionObject message\n\
#Takes current object in the environment and removes it as\n\
#a regular object\n\
byte ATTACH_AND_REMOVE_AS_OBJECT=3\n\
\n\
# Byte code for operation\n\
byte operation\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/AttachedCollisionObject\n\
# The CollisionObject will be attached with a fixed joint to this link\n\
# If link name is set to REMOVE_ALL_ATTACHED_OBJECTS and object.operation \n\
# is set to REMOVE will remove all attached bodies attached to any object\n\
string link_name\n\
\n\
#Reserved for indicating that all attached objects should be removed\n\
string REMOVE_ALL_ATTACHED_OBJECTS = \"all\"\n\
\n\
#This contains the actual shapes and poses for the CollisionObject\n\
#to be attached to the link\n\
#If action is remove and no object.id is set, all objects\n\
#attached to the link indicated by link_name will be removed\n\
CollisionObject object\n\
\n\
# The set of links that the attached objects are allowed to touch\n\
# by default - the link_name is included by default\n\
string[] touch_links\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/CollisionMap\n\
#header for interpreting box positions\n\
Header header\n\
\n\
#boxes for use in collision testing\n\
OrientedBoundingBox[] boxes\n\
\n\
================================================================================\n\
MSG: arm_navigation_msgs/OrientedBoundingBox\n\
#the center of the box\n\
geometry_msgs/Point32 center\n\
\n\
#the extents of the box, assuming the center is at the point\n\
geometry_msgs/Point32 extents\n\
\n\
#the axis of the box\n\
geometry_msgs/Point32 axis\n\
\n\
#the angle of rotation around the axis\n\
float32 angle\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const  ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.robot_state);
    stream.next(m.fixed_frame_transforms);
    stream.next(m.allowed_collision_matrix);
    stream.next(m.allowed_contacts);
    stream.next(m.link_padding);
    stream.next(m.collision_objects);
    stream.next(m.attached_collision_objects);
    stream.next(m.collision_map);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PlanningScene_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_navigation_msgs::PlanningScene_<ContainerAllocator> & v) 
  {
    s << indent << "robot_state: ";
s << std::endl;
    Printer< ::arm_navigation_msgs::RobotState_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_state);
    s << indent << "fixed_frame_transforms[]" << std::endl;
    for (size_t i = 0; i < v.fixed_frame_transforms.size(); ++i)
    {
      s << indent << "  fixed_frame_transforms[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.fixed_frame_transforms[i]);
    }
    s << indent << "allowed_collision_matrix: ";
s << std::endl;
    Printer< ::arm_navigation_msgs::AllowedCollisionMatrix_<ContainerAllocator> >::stream(s, indent + "  ", v.allowed_collision_matrix);
    s << indent << "allowed_contacts[]" << std::endl;
    for (size_t i = 0; i < v.allowed_contacts.size(); ++i)
    {
      s << indent << "  allowed_contacts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::arm_navigation_msgs::AllowedContactSpecification_<ContainerAllocator> >::stream(s, indent + "    ", v.allowed_contacts[i]);
    }
    s << indent << "link_padding[]" << std::endl;
    for (size_t i = 0; i < v.link_padding.size(); ++i)
    {
      s << indent << "  link_padding[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::arm_navigation_msgs::LinkPadding_<ContainerAllocator> >::stream(s, indent + "    ", v.link_padding[i]);
    }
    s << indent << "collision_objects[]" << std::endl;
    for (size_t i = 0; i < v.collision_objects.size(); ++i)
    {
      s << indent << "  collision_objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::arm_navigation_msgs::CollisionObject_<ContainerAllocator> >::stream(s, indent + "    ", v.collision_objects[i]);
    }
    s << indent << "attached_collision_objects[]" << std::endl;
    for (size_t i = 0; i < v.attached_collision_objects.size(); ++i)
    {
      s << indent << "  attached_collision_objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::arm_navigation_msgs::AttachedCollisionObject_<ContainerAllocator> >::stream(s, indent + "    ", v.attached_collision_objects[i]);
    }
    s << indent << "collision_map: ";
s << std::endl;
    Printer< ::arm_navigation_msgs::CollisionMap_<ContainerAllocator> >::stream(s, indent + "  ", v.collision_map);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_NAVIGATION_MSGS_MESSAGE_PLANNINGSCENE_H

