/* Auto-generated by genmsg_cpp for file /home/beryl/fuerte_workspace/sandbox/humanoid_navigation_ros/arm_navigation/arm_navigation_msgs/msg/SyncPlanningSceneFeedback.msg */
#ifndef ARM_NAVIGATION_MSGS_MESSAGE_SYNCPLANNINGSCENEFEEDBACK_H
#define ARM_NAVIGATION_MSGS_MESSAGE_SYNCPLANNINGSCENEFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arm_navigation_msgs
{
template <class ContainerAllocator>
struct SyncPlanningSceneFeedback_ {
  typedef SyncPlanningSceneFeedback_<ContainerAllocator> Type;

  SyncPlanningSceneFeedback_()
  : client_processing(false)
  , ready(false)
  {
  }

  SyncPlanningSceneFeedback_(const ContainerAllocator& _alloc)
  : client_processing(false)
  , ready(false)
  {
  }

  typedef uint8_t _client_processing_type;
  uint8_t client_processing;

  typedef uint8_t _ready_type;
  uint8_t ready;


  typedef boost::shared_ptr< ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SyncPlanningSceneFeedback
typedef  ::arm_navigation_msgs::SyncPlanningSceneFeedback_<std::allocator<void> > SyncPlanningSceneFeedback;

typedef boost::shared_ptr< ::arm_navigation_msgs::SyncPlanningSceneFeedback> SyncPlanningSceneFeedbackPtr;
typedef boost::shared_ptr< ::arm_navigation_msgs::SyncPlanningSceneFeedback const> SyncPlanningSceneFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_navigation_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5470cffcd2540df5b10d2ed9ddfde7e4";
  }

  static const char* value(const  ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5470cffcd2540df5ULL;
  static const uint64_t static_value2 = 0xb10d2ed9ddfde7e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_navigation_msgs/SyncPlanningSceneFeedback";
  }

  static const char* value(const  ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool client_processing\n\
bool ready\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.client_processing);
    stream.next(m.ready);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SyncPlanningSceneFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_navigation_msgs::SyncPlanningSceneFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "client_processing: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.client_processing);
    s << indent << "ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ready);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_NAVIGATION_MSGS_MESSAGE_SYNCPLANNINGSCENEFEEDBACK_H

