(cl:in-package arm_navigation_msgs-srv)
(cl:export '(TRAJECTORY-VAL
          TRAJECTORY
          ROBOT_STATE-VAL
          ROBOT_STATE
          CHECK_COLLISIONS-VAL
          CHECK_COLLISIONS
          CHECK_PATH_CONSTRAINTS-VAL
          CHECK_PATH_CONSTRAINTS
          CHECK_GOAL_CONSTRAINTS-VAL
          CHECK_GOAL_CONSTRAINTS
          CHECK_JOINT_LIMITS-VAL
          CHECK_JOINT_LIMITS
          CHECK_FULL_TRAJECTORY-VAL
          CHECK_FULL_TRAJECTORY
          PATH_CONSTRAINTS-VAL
          PATH_CONSTRAINTS
          GOAL_CONSTRAINTS-VAL
          GOAL_CONSTRAINTS
          ERROR_CODE-VAL
          ERROR_CODE
          TRAJECTORY_ERROR_CODES-VAL
          TRAJECTORY_ERROR_CODES
          CONTACTS-VAL
          CONTACTS
))