(cl:defpackage spline_smoother-msg
  (:use )
  (:export
   "<LSPBTRAJECTORYMSG>"
   "LSPBTRAJECTORYMSG"
   "<SPLINETRAJECTORYSEGMENT>"
   "SPLINETRAJECTORYSEGMENT"
   "<SPLINETRAJECTORY>"
   "SPLINETRAJECTORY"
   "<LSPBTRAJECTORYSEGMENTMSG>"
   "LSPBTRAJECTORYSEGMENTMSG"
   "<LSPBSPLINECOEFFICIENTS>"
   "LSPBSPLINECOEFFICIENTS"
   "<SPLINECOEFFICIENTS>"
   "SPLINECOEFFICIENTS"
  ))

