(cl:defpackage humanoid_nav_msgs-srv
  (:use )
  (:export
   "STEPTARGETSERVICE"
   "<STEPTARGETSERVICE-REQUEST>"
   "STEPTARGETSERVICE-REQUEST"
   "<STEPTARGETSERVICE-RESPONSE>"
   "STEPTARGETSERVICE-RESPONSE"
   "PLANFOOTSTEPS"
   "<PLANFOOTSTEPS-REQUEST>"
   "PLANFOOTSTEPS-REQUEST"
   "<PLANFOOTSTEPS-RESPONSE>"
   "PLANFOOTSTEPS-RESPONSE"
  ))

