(cl:defpackage kinematics_msgs-srv
  (:use )
  (:export
   "GETCONSTRAINTAWAREPOSITIONIK"
   "<GETCONSTRAINTAWAREPOSITIONIK-REQUEST>"
   "GETCONSTRAINTAWAREPOSITIONIK-REQUEST"
   "<GETCONSTRAINTAWAREPOSITIONIK-RESPONSE>"
   "GETCONSTRAINTAWAREPOSITIONIK-RESPONSE"
   "GETPOSITIONIK"
   "<GETPOSITIONIK-REQUEST>"
   "GETPOSITIONIK-REQUEST"
   "<GETPOSITIONIK-RESPONSE>"
   "GETPOSITIONIK-RESPONSE"
   "GETKINEMATICSOLVERINFO"
   "<GETKINEMATICSOLVERINFO-REQUEST>"
   "GETKINEMATICSOLVERINFO-REQUEST"
   "<GETKINEMATICSOLVERINFO-RESPONSE>"
   "GETKINEMATICSOLVERINFO-RESPONSE"
   "GETPOSITIONFK"
   "<GETPOSITIONFK-REQUEST>"
   "GETPOSITIONFK-REQUEST"
   "<GETPOSITIONFK-RESPONSE>"
   "GETPOSITIONFK-RESPONSE"
  ))

