(cl:in-package arm_navigation_msgs-msg)
(cl:export '(ROBOT_STATE-VAL
          ROBOT_STATE
          FIXED_FRAME_TRANSFORMS-VAL
          FIXED_FRAME_TRANSFORMS
          ALLOWED_COLLISION_MATRIX-VAL
          ALLOWED_COLLISION_MATRIX
          ALLOWED_CONTACTS-VAL
          ALLOWED_CONTACTS
          LINK_PADDING-VAL
          LINK_PADDING
          COLLISION_OBJECTS-VAL
          COLLISION_OBJECTS
          ATTACHED_COLLISION_OBJECTS-VAL
          ATTACHED_COLLISION_OBJECTS
          COLLISION_MAP-VAL
          COLLISION_MAP
))