(cl:in-package arm_navigation_msgs-msg)
(cl:export '(PLANNER_SERVICE_NAME-VAL
          PLANNER_SERVICE_NAME
          PLANNING_SCENE_DIFF-VAL
          PLANNING_SCENE_DIFF
          MOTION_PLAN_REQUEST-VAL
          MOTION_PLAN_REQUEST
          OPERATIONS-VAL
          OPERATIONS
          ACCEPT_PARTIAL_PLANS-VAL
          ACCEPT_PARTIAL_PLANS
          ACCEPT_INVALID_GOALS-VAL
          ACCEPT_INVALID_GOALS
          DISABLE_IK-VAL
          DISABLE_IK
          DISABLE_COLLISION_MONITORING-VAL
          DISABLE_COLLISION_MONITORING
))