(cl:in-package arm_navigation_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LINK_NAME-VAL
          LINK_NAME
          POSE-VAL
          POSE
          ABSOLUTE_POSITION_TOLERANCE-VAL
          ABSOLUTE_POSITION_TOLERANCE
          ABSOLUTE_ROLL_TOLERANCE-VAL
          ABSOLUTE_ROLL_TOLERANCE
          ABSOLUTE_YAW_TOLERANCE-VAL
          ABSOLUTE_YAW_TOLERANCE
          ABSOLUTE_PITCH_TOLERANCE-VAL
          ABSOLUTE_PITCH_TOLERANCE
          ORIENTATION_CONSTRAINT_TYPE-VAL
          ORIENTATION_CONSTRAINT_TYPE
))