; Auto-generated. Do not edit!


(cl:in-package arm_navigation_msgs-msg)


;//! \htmlinclude MakeStaticCollisionMapResult.msg.html

(cl:defclass <MakeStaticCollisionMapResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MakeStaticCollisionMapResult (<MakeStaticCollisionMapResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MakeStaticCollisionMapResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MakeStaticCollisionMapResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_navigation_msgs-msg:<MakeStaticCollisionMapResult> is deprecated: use arm_navigation_msgs-msg:MakeStaticCollisionMapResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MakeStaticCollisionMapResult>) ostream)
  "Serializes a message object of type '<MakeStaticCollisionMapResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MakeStaticCollisionMapResult>) istream)
  "Deserializes a message object of type '<MakeStaticCollisionMapResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MakeStaticCollisionMapResult>)))
  "Returns string type for a message object of type '<MakeStaticCollisionMapResult>"
  "arm_navigation_msgs/MakeStaticCollisionMapResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MakeStaticCollisionMapResult)))
  "Returns string type for a message object of type 'MakeStaticCollisionMapResult"
  "arm_navigation_msgs/MakeStaticCollisionMapResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MakeStaticCollisionMapResult>)))
  "Returns md5sum for a message object of type '<MakeStaticCollisionMapResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MakeStaticCollisionMapResult)))
  "Returns md5sum for a message object of type 'MakeStaticCollisionMapResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MakeStaticCollisionMapResult>)))
  "Returns full string definition for message of type '<MakeStaticCollisionMapResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MakeStaticCollisionMapResult)))
  "Returns full string definition for message of type 'MakeStaticCollisionMapResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MakeStaticCollisionMapResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MakeStaticCollisionMapResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MakeStaticCollisionMapResult
))
