; Auto-generated. Do not edit!


(cl:in-package arm_navigation_msgs-msg)


;//! \htmlinclude MakeStaticCollisionMapGoal.msg.html

(cl:defclass <MakeStaticCollisionMapGoal> (roslisp-msg-protocol:ros-message)
  ((cloud_source
    :reader cloud_source
    :initarg :cloud_source
    :type cl:string
    :initform "")
   (number_of_clouds
    :reader number_of_clouds
    :initarg :number_of_clouds
    :type cl:integer
    :initform 0))
)

(cl:defclass MakeStaticCollisionMapGoal (<MakeStaticCollisionMapGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MakeStaticCollisionMapGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MakeStaticCollisionMapGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_navigation_msgs-msg:<MakeStaticCollisionMapGoal> is deprecated: use arm_navigation_msgs-msg:MakeStaticCollisionMapGoal instead.")))

(cl:ensure-generic-function 'cloud_source-val :lambda-list '(m))
(cl:defmethod cloud_source-val ((m <MakeStaticCollisionMapGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_navigation_msgs-msg:cloud_source-val is deprecated.  Use arm_navigation_msgs-msg:cloud_source instead.")
  (cloud_source m))

(cl:ensure-generic-function 'number_of_clouds-val :lambda-list '(m))
(cl:defmethod number_of_clouds-val ((m <MakeStaticCollisionMapGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_navigation_msgs-msg:number_of_clouds-val is deprecated.  Use arm_navigation_msgs-msg:number_of_clouds instead.")
  (number_of_clouds m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MakeStaticCollisionMapGoal>) ostream)
  "Serializes a message object of type '<MakeStaticCollisionMapGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'cloud_source))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'cloud_source))
  (cl:let* ((signed (cl:slot-value msg 'number_of_clouds)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MakeStaticCollisionMapGoal>) istream)
  "Deserializes a message object of type '<MakeStaticCollisionMapGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'cloud_source) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'cloud_source) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'number_of_clouds) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MakeStaticCollisionMapGoal>)))
  "Returns string type for a message object of type '<MakeStaticCollisionMapGoal>"
  "arm_navigation_msgs/MakeStaticCollisionMapGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MakeStaticCollisionMapGoal)))
  "Returns string type for a message object of type 'MakeStaticCollisionMapGoal"
  "arm_navigation_msgs/MakeStaticCollisionMapGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MakeStaticCollisionMapGoal>)))
  "Returns md5sum for a message object of type '<MakeStaticCollisionMapGoal>"
  "43564281ea7e3c1ca0f01095edc909f7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MakeStaticCollisionMapGoal)))
  "Returns md5sum for a message object of type 'MakeStaticCollisionMapGoal"
  "43564281ea7e3c1ca0f01095edc909f7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MakeStaticCollisionMapGoal>)))
  "Returns full string definition for message of type '<MakeStaticCollisionMapGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#The source to use to make the stable map~%string cloud_source~%~%#The number of clouds to compose the stable map~%int32 number_of_clouds~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MakeStaticCollisionMapGoal)))
  "Returns full string definition for message of type 'MakeStaticCollisionMapGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#The source to use to make the stable map~%string cloud_source~%~%#The number of clouds to compose the stable map~%int32 number_of_clouds~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MakeStaticCollisionMapGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'cloud_source))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MakeStaticCollisionMapGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MakeStaticCollisionMapGoal
    (cl:cons ':cloud_source (cloud_source msg))
    (cl:cons ':number_of_clouds (number_of_clouds msg))
))
