; Auto-generated. Do not edit!


(cl:in-package arm_navigation_msgs-msg)


;//! \htmlinclude SyncPlanningSceneFeedback.msg.html

(cl:defclass <SyncPlanningSceneFeedback> (roslisp-msg-protocol:ros-message)
  ((client_processing
    :reader client_processing
    :initarg :client_processing
    :type cl:boolean
    :initform cl:nil)
   (ready
    :reader ready
    :initarg :ready
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SyncPlanningSceneFeedback (<SyncPlanningSceneFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SyncPlanningSceneFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SyncPlanningSceneFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_navigation_msgs-msg:<SyncPlanningSceneFeedback> is deprecated: use arm_navigation_msgs-msg:SyncPlanningSceneFeedback instead.")))

(cl:ensure-generic-function 'client_processing-val :lambda-list '(m))
(cl:defmethod client_processing-val ((m <SyncPlanningSceneFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_navigation_msgs-msg:client_processing-val is deprecated.  Use arm_navigation_msgs-msg:client_processing instead.")
  (client_processing m))

(cl:ensure-generic-function 'ready-val :lambda-list '(m))
(cl:defmethod ready-val ((m <SyncPlanningSceneFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_navigation_msgs-msg:ready-val is deprecated.  Use arm_navigation_msgs-msg:ready instead.")
  (ready m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SyncPlanningSceneFeedback>) ostream)
  "Serializes a message object of type '<SyncPlanningSceneFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'client_processing) 1 0)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'ready) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SyncPlanningSceneFeedback>) istream)
  "Deserializes a message object of type '<SyncPlanningSceneFeedback>"
    (cl:setf (cl:slot-value msg 'client_processing) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:setf (cl:slot-value msg 'ready) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SyncPlanningSceneFeedback>)))
  "Returns string type for a message object of type '<SyncPlanningSceneFeedback>"
  "arm_navigation_msgs/SyncPlanningSceneFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SyncPlanningSceneFeedback)))
  "Returns string type for a message object of type 'SyncPlanningSceneFeedback"
  "arm_navigation_msgs/SyncPlanningSceneFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SyncPlanningSceneFeedback>)))
  "Returns md5sum for a message object of type '<SyncPlanningSceneFeedback>"
  "5470cffcd2540df5b10d2ed9ddfde7e4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SyncPlanningSceneFeedback)))
  "Returns md5sum for a message object of type 'SyncPlanningSceneFeedback"
  "5470cffcd2540df5b10d2ed9ddfde7e4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SyncPlanningSceneFeedback>)))
  "Returns full string definition for message of type '<SyncPlanningSceneFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool client_processing~%bool ready~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SyncPlanningSceneFeedback)))
  "Returns full string definition for message of type 'SyncPlanningSceneFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool client_processing~%bool ready~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SyncPlanningSceneFeedback>))
  (cl:+ 0
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SyncPlanningSceneFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SyncPlanningSceneFeedback
    (cl:cons ':client_processing (client_processing msg))
    (cl:cons ':ready (ready msg))
))
